/* ========================================================================
   ピクロス JP→EN 辞書
   絵にできる具象名詞を中心に、Iconify で形になる語を厳選。
   value は string または string[]（複数訳。先頭が代表訳）
   ======================================================================== */

(function (root) {
  "use strict";

  const JP_TO_EN = {
    // ====== 動物 ======
    // 哺乳類
    "猫": "cat", "ねこ": "cat", "ネコ": "cat", "子猫": "kitten", "黒猫": "cat",
    "犬": "dog", "いぬ": "dog", "イヌ": "dog", "子犬": "puppy", "ポメラニアン": "dog", "柴犬": "dog", "ブルドッグ": "bulldog", "プードル": "poodle",
    "うさぎ": "rabbit", "ウサギ": "rabbit", "兎": "rabbit", "ラビット": "rabbit",
    "象": "elephant", "ぞう": "elephant", "ゾウ": "elephant",
    "ライオン": "lion", "獅子": "lion",
    "虎": "tiger", "とら": "tiger", "トラ": "tiger",
    "豹": "leopard", "ヒョウ": "leopard", "チーター": "cheetah",
    "パンダ": "panda",
    "コアラ": "koala",
    "カンガルー": "kangaroo",
    "サル": "monkey", "猿": "monkey", "さる": "monkey",
    "ゴリラ": "gorilla",
    "チンパンジー": "chimpanzee",
    "馬": "horse", "うま": "horse", "ウマ": "horse", "子馬": "horse",
    "牛": "cow", "うし": "cow", "ウシ": "cow", "子牛": "calf",
    "豚": "pig", "ぶた": "pig", "ブタ": "pig",
    "羊": "sheep", "ひつじ": "sheep", "ヒツジ": "sheep",
    "山羊": "goat", "やぎ": "goat", "ヤギ": "goat",
    "鹿": "deer", "しか": "deer", "シカ": "deer", "バンビ": "deer",
    "トナカイ": "reindeer",
    "ロバ": "donkey",
    "ラクダ": "camel",
    "キリン": "giraffe",
    "シマウマ": "zebra",
    "サイ": "rhino", "犀": "rhino",
    "カバ": "hippo",
    "狐": "fox", "きつね": "fox", "キツネ": "fox",
    "狼": "wolf", "おおかみ": "wolf", "オオカミ": "wolf",
    "熊": "bear", "くま": "bear", "クマ": "bear",
    "シロクマ": "polar-bear", "白熊": "polar-bear",
    "ハムスター": "hamster",
    "リス": "squirrel", "栗鼠": "squirrel",
    "ねずみ": "mouse", "ネズミ": "mouse", "鼠": "mouse",
    "ラット": "rat",
    "ハリネズミ": "hedgehog",
    "アライグマ": "raccoon",
    "ビーバー": "beaver",
    "もぐら": "mole", "モグラ": "mole",
    "コウモリ": "bat", "蝙蝠": "bat",
    "ナマケモノ": "sloth",
    "アルマジロ": "armadillo",
    "カピバラ": "capybara",
    "アザラシ": "seal",
    "アシカ": "seal",
    "セイウチ": "walrus",
    "ペンギン": "penguin",
    // 海洋
    "魚": "fish", "さかな": "fish", "サカナ": "fish",
    "金魚": "goldfish",
    "鯉": "carp", "コイ": "carp",
    "鯛": "fish",
    "鮪": "tuna", "マグロ": "tuna",
    "鮭": "salmon", "サケ": "salmon", "サーモン": "salmon",
    "鯵": "fish", "アジ": "fish",
    "鰯": "fish", "イワシ": "fish",
    "イルカ": "dolphin", "いるか": "dolphin",
    "鯨": "whale", "くじら": "whale", "クジラ": "whale",
    "サメ": "shark", "鮫": "shark",
    "タコ": "octopus", "たこ": "octopus", "蛸": "octopus",
    "イカ": "squid", "烏賊": "squid",
    "クラゲ": "jellyfish", "海月": "jellyfish",
    "亀": "turtle", "かめ": "turtle", "カメ": "turtle",
    "海老": "shrimp", "エビ": "shrimp", "えび": "shrimp",
    "蟹": "crab", "カニ": "crab", "かに": "crab",
    "貝": "shell",
    "ヒトデ": "starfish",
    "サンゴ": "coral",
    "シーホース": "seahorse", "タツノオトシゴ": "seahorse",
    // 鳥
    "鳥": "bird", "とり": "bird", "トリ": "bird",
    "鷲": "eagle", "わし": "eagle",
    "鷹": "hawk", "たか": "hawk",
    "フクロウ": "owl", "ふくろう": "owl", "梟": "owl",
    "鶏": "chicken", "にわとり": "chicken", "ニワトリ": "chicken",
    "ひよこ": "chick", "ヒヨコ": "chick",
    "アヒル": "duck", "あひる": "duck", "鴨": "duck",
    "白鳥": "swan", "ハクチョウ": "swan",
    "鶴": "crane", "ツル": "crane",
    "鷺": "heron",
    "雀": "sparrow", "スズメ": "sparrow",
    "鳩": "dove", "ハト": "pigeon", "はと": "dove",
    "カラス": "crow", "烏": "crow",
    "ペンギン": "penguin",
    "孔雀": "peacock", "クジャク": "peacock",
    "ペリカン": "pelican",
    "フラミンゴ": "flamingo",
    "オウム": "parrot", "鸚鵡": "parrot",
    "インコ": "parrot",
    "ハチドリ": "hummingbird",
    "キツツキ": "woodpecker",
    "ツバメ": "swallow", "燕": "swallow",
    // 昆虫
    "蝶": "butterfly", "ちょう": "butterfly", "チョウ": "butterfly", "蝶々": "butterfly",
    "蛾": "moth",
    "蜂": "bee", "はち": "bee", "ハチ": "bee", "ミツバチ": "bee",
    "蟻": "ant", "あり": "ant", "アリ": "ant",
    "蜘蛛": "spider", "クモ": "spider", "くも": "spider",
    "蝉": "cicada", "セミ": "cicada",
    "蛍": "firefly", "ホタル": "firefly",
    "テントウムシ": "ladybug", "天道虫": "ladybug",
    "カブトムシ": "beetle", "兜虫": "beetle",
    "クワガタ": "beetle",
    "トンボ": "dragonfly", "蜻蛉": "dragonfly",
    "バッタ": "grasshopper",
    "コオロギ": "cricket",
    "ゴキブリ": "cockroach",
    "毛虫": "caterpillar", "イモムシ": "caterpillar",
    // 爬虫類・両生類
    "蛇": "snake", "へび": "snake", "ヘビ": "snake",
    "トカゲ": "lizard", "蜥蜴": "lizard",
    "ヤモリ": "gecko",
    "イモリ": "newt",
    "カメレオン": "chameleon",
    "ワニ": "crocodile", "鰐": "crocodile",
    "蛙": "frog", "かえる": "frog", "カエル": "frog",
    "オタマジャクシ": "tadpole",
    // 想像
    "ドラゴン": "dragon", "竜": "dragon", "龍": "dragon",
    "ユニコーン": "unicorn", "一角獣": "unicorn",
    "ペガサス": "pegasus",
    "恐竜": "dinosaur", "きょうりゅう": "dinosaur",
    "ティラノサウルス": "dinosaur",
    "ステゴサウルス": "dinosaur",
    "プテラノドン": "dinosaur",
    "マンモス": "mammoth",
    "マーメイド": "mermaid", "人魚": "mermaid",
    "妖精": "fairy", "フェアリー": "fairy",
    "幽霊": "ghost", "ゴースト": "ghost", "おばけ": "ghost", "お化け": "ghost",
    "悪魔": "devil", "あくま": "devil", "デビル": "devil",
    "天使": "angel", "てんし": "angel",
    "宇宙人": "alien", "エイリアン": "alien",
    "鬼": "ogre", "おに": "ogre", "オニ": "ogre",
    "魔女": "witch",
    "魔法使い": "wizard",
    "ロボット": "robot", "ろぼっと": "robot",
    "ゾンビ": "zombie",
    "ミイラ": "mummy",
    "ヴァンパイア": "vampire", "吸血鬼": "vampire",

    // ====== 植物・花 ======
    "木": "tree", "き": "tree",
    "森": "forest", "もり": "forest",
    "竹": "bamboo", "たけ": "bamboo",
    "松": "pine", "まつ": "pine",
    "椰子": "palm-tree", "ヤシ": "palm-tree", "やし": "palm-tree", "ヤシの木": "palm-tree",
    "サボテン": "cactus", "仙人掌": "cactus",
    "切り株": "stump",
    "葉": "leaf", "は": "leaf", "葉っぱ": "leaf",
    "枝": "branch", "えだ": "branch",
    "実": "fruit",
    "種": "seed", "たね": "seed",
    "花": "flower", "はな": "flower",
    "桜": "sakura", "さくら": "sakura", "サクラ": "sakura", "桜の花": "cherry-blossom",
    "紅葉": "maple-leaf", "もみじ": "maple-leaf", "モミジ": "maple-leaf", "楓": "maple-leaf",
    "梅": "plum-blossom", "うめ": "plum-blossom", "梅の花": "plum-blossom",
    "バラ": "rose", "ばら": "rose", "薔薇": "rose",
    "ひまわり": "sunflower", "ヒマワリ": "sunflower", "向日葵": "sunflower",
    "チューリップ": "tulip",
    "ユリ": "lily", "百合": "lily",
    "蓮": "lotus", "ハス": "lotus",
    "あじさい": "hydrangea", "紫陽花": "hydrangea",
    "コスモス": "cosmos",
    "菊": "chrysanthemum", "キク": "chrysanthemum",
    "カーネーション": "carnation",
    "蘭": "orchid", "ラン": "orchid", "オーキッド": "orchid",
    "デイジー": "daisy", "ヒナギク": "daisy",
    "クローバー": "clover", "四つ葉": "clover",
    "つくし": "horsetail",
    "タンポポ": "dandelion", "蒲公英": "dandelion",
    "アサガオ": "morning-glory", "朝顔": "morning-glory",
    "椿": "camellia",
    "苔": "moss",
    "キノコ": "mushroom", "きのこ": "mushroom", "茸": "mushroom",

    // ====== 食べ物・飲み物 ======
    // 果物
    "りんご": "apple", "リンゴ": "apple", "林檎": "apple",
    "オレンジ": "orange",
    "みかん": "tangerine", "蜜柑": "tangerine", "ミカン": "tangerine",
    "バナナ": "banana",
    "イチゴ": "strawberry", "いちご": "strawberry", "苺": "strawberry",
    "スイカ": "watermelon", "すいか": "watermelon", "西瓜": "watermelon",
    "メロン": "melon",
    "パイナップル": "pineapple",
    "レモン": "lemon", "檸檬": "lemon",
    "ライム": "lime",
    "ぶどう": "grapes", "葡萄": "grapes", "ブドウ": "grapes",
    "桃": "peach", "もも": "peach",
    "さくらんぼ": "cherry", "サクランボ": "cherry", "桜桃": "cherry",
    "梨": "pear", "なし": "pear", "ナシ": "pear",
    "柿": "persimmon", "かき": "persimmon",
    "栗": "chestnut", "クリ": "chestnut",
    "キウイ": "kiwi",
    "マンゴー": "mango",
    "アボカド": "avocado",
    "ココナッツ": "coconut",
    "ブルーベリー": "blueberry",
    "ラズベリー": "raspberry",
    "イチジク": "fig", "無花果": "fig",
    "ザクロ": "pomegranate", "石榴": "pomegranate",
    // 野菜
    "ニンジン": "carrot", "にんじん": "carrot", "人参": "carrot",
    "トマト": "tomato",
    "玉ねぎ": "onion", "たまねぎ": "onion", "玉葱": "onion",
    "ジャガイモ": "potato", "じゃがいも": "potato",
    "サツマイモ": "sweet-potato", "さつまいも": "sweet-potato",
    "ブロッコリー": "broccoli",
    "カリフラワー": "cauliflower",
    "ナス": "eggplant", "茄子": "eggplant", "なす": "eggplant",
    "キュウリ": "cucumber", "胡瓜": "cucumber", "きゅうり": "cucumber",
    "ピーマン": "bell-pepper",
    "唐辛子": "pepper", "とうがらし": "pepper", "トウガラシ": "pepper",
    "とうもろこし": "corn", "コーン": "corn", "玉蜀黍": "corn",
    "カボチャ": "pumpkin", "南瓜": "pumpkin", "かぼちゃ": "pumpkin",
    "大根": "radish", "だいこん": "radish",
    "白菜": "cabbage",
    "キャベツ": "cabbage",
    "レタス": "lettuce",
    "ほうれん草": "spinach",
    "セロリ": "celery",
    "アスパラ": "asparagus",
    "豆": "bean", "まめ": "bean",
    "枝豆": "edamame",
    "ニンニク": "garlic", "にんにく": "garlic",
    "ショウガ": "ginger", "生姜": "ginger",
    "ネギ": "leek", "葱": "leek",
    "ごぼう": "burdock",
    "オクラ": "okra",
    // 主食・調理品
    "パン": "bread", "食パン": "bread",
    "ご飯": "rice", "ごはん": "rice", "米": "rice", "おにぎり": "onigiri",
    "おむすび": "onigiri",
    "餅": "mochi", "もち": "mochi", "モチ": "mochi",
    "団子": "dango", "だんご": "dango",
    "麺": "noodle",
    "ラーメン": "ramen",
    "うどん": "udon",
    "そば": "soba",
    "蕎麦": "soba",
    "パスタ": "pasta", "スパゲッティ": "spaghetti",
    "ピザ": "pizza",
    "ハンバーガー": "hamburger",
    "バーガー": "burger",
    "ホットドッグ": "hot-dog",
    "サンドイッチ": "sandwich",
    "寿司": "sushi", "すし": "sushi",
    "刺身": "sashimi",
    "天ぷら": "tempura",
    "餃子": "dumpling", "ぎょうざ": "dumpling",
    "肉まん": "bun",
    "チャーハン": "fried-rice",
    "カレー": "curry",
    "スープ": "soup",
    "サラダ": "salad",
    "卵": "egg", "たまご": "egg", "玉子": "egg",
    "目玉焼き": "fried-egg",
    "オムレツ": "omelet",
    "肉": "meat", "にく": "meat",
    "ステーキ": "steak",
    "ベーコン": "bacon",
    "ソーセージ": "sausage",
    "チーズ": "cheese",
    "バター": "butter",
    "ヨーグルト": "yogurt",
    "牛乳": "milk", "ミルク": "milk",
    // スイーツ
    "ケーキ": "cake",
    "ショートケーキ": "shortcake",
    "カップケーキ": "cupcake",
    "チーズケーキ": "cheesecake",
    "ドーナツ": "donut",
    "アイス": "ice-cream", "アイスクリーム": "ice-cream",
    "ソフトクリーム": "ice-cream",
    "クッキー": "cookie",
    "ビスケット": "biscuit",
    "チョコ": "chocolate", "チョコレート": "chocolate",
    "キャンディ": "candy", "飴": "candy", "あめ": "candy",
    "ロリポップ": "lollipop",
    "プリン": "pudding",
    "プディング": "pudding",
    "わたあめ": "cotton-candy", "綿菓子": "cotton-candy",
    "マカロン": "macaron",
    "マフィン": "muffin",
    "クロワッサン": "croissant",
    "パンケーキ": "pancake", "ホットケーキ": "pancake",
    "ワッフル": "waffle",
    "プレッツェル": "pretzel",
    "あんパン": "bread",
    "ポップコーン": "popcorn",
    "ガム": "gum",
    "ハチミツ": "honey", "蜂蜜": "honey",
    "ジャム": "jam",
    // 飲み物
    "水": "water", "みず": "water",
    "お茶": "tea", "おちゃ": "tea", "茶": "tea",
    "紅茶": "tea",
    "緑茶": "tea",
    "抹茶": "matcha",
    "コーヒー": "coffee", "珈琲": "coffee",
    "カフェラテ": "latte",
    "ジュース": "juice",
    "牛乳": "milk", "ミルク": "milk",
    "ココア": "cocoa",
    "ビール": "beer",
    "ワイン": "wine",
    "シャンパン": "champagne",
    "カクテル": "cocktail",
    "ウィスキー": "whisky",
    "日本酒": "sake",
    "酒": "sake",
    "サイダー": "soda",
    "コーラ": "cola",

    // ====== 自然・天体 ======
    "山": "mountain", "やま": "mountain", "富士山": "mountain",
    "丘": "hill",
    "火山": "volcano", "かざん": "volcano",
    "海": "ocean", "うみ": "ocean", "海洋": "ocean",
    "波": "wave", "なみ": "wave",
    "川": "river", "かわ": "river",
    "湖": "lake", "みずうみ": "lake",
    "滝": "waterfall", "たき": "waterfall",
    "泉": "spring",
    "島": "island", "しま": "island",
    "砂漠": "desert",
    "オアシス": "oasis",
    "森": "forest",
    "草": "grass",
    "石": "stone", "いし": "stone",
    "岩": "rock", "いわ": "rock",
    "土": "soil",
    "砂": "sand",
    "雪": "snow", "ゆき": "snow",
    "氷": "ice", "こおり": "ice",
    "氷山": "iceberg",
    "雨": "rain", "あめ": "rain",
    "雷": "lightning", "かみなり": "lightning",
    "稲妻": "lightning",
    "風": "wind",
    "竜巻": "tornado", "トルネード": "tornado",
    "嵐": "storm",
    "雲": "cloud", "くも": "cloud",
    "霧": "fog", "きり": "fog",
    "虹": "rainbow", "にじ": "rainbow",
    "太陽": "sun", "たいよう": "sun", "おひさま": "sun", "日": "sun",
    "月": "moon", "つき": "moon", "三日月": "crescent-moon",
    "満月": "moon",
    "星": "star", "ほし": "star",
    "流れ星": "shooting-star",
    "彗星": "comet",
    "惑星": "planet",
    "土星": "saturn",
    "地球": "earth", "ちきゅう": "earth",
    "宇宙": "galaxy", "銀河": "galaxy",
    "雪の結晶": "snowflake", "結晶": "snowflake",
    "雪だるま": "snowman",
    "火": "fire", "ひ": "fire", "炎": "flame", "ほのお": "flame",
    "煙": "smoke", "けむり": "smoke",
    "影": "shadow",
    "光": "light", "ひかり": "light",

    // ====== 乗り物 ======
    "車": "car", "くるま": "car", "自動車": "car",
    "スポーツカー": "car",
    "バス": "bus",
    "トラック": "truck",
    "電車": "train", "でんしゃ": "train",
    "新幹線": "train",
    "蒸気機関車": "train",
    "地下鉄": "subway",
    "モノレール": "train",
    "飛行機": "airplane", "ひこうき": "airplane",
    "ヘリコプター": "helicopter", "ヘリ": "helicopter",
    "気球": "hot-air-balloon",
    "船": "ship", "ふね": "ship",
    "ヨット": "sailboat", "ヨットボート": "sailboat",
    "ボート": "boat",
    "潜水艦": "submarine",
    "イカダ": "raft",
    "自転車": "bicycle", "じてんしゃ": "bicycle",
    "バイク": "motorcycle", "オートバイ": "motorcycle",
    "スクーター": "scooter",
    "ロケット": "rocket",
    "ロケットミサイル": "rocket",
    "宇宙船": "spaceship",
    "UFO": "ufo",
    "タクシー": "taxi",
    "パトカー": "police-car",
    "消防車": "fire-truck",
    "救急車": "ambulance",
    "戦車": "tank",
    "三輪車": "tricycle",
    "ベビーカー": "stroller",
    "馬車": "carriage",
    "リムジン": "limousine",
    "ガソリン": "fuel",

    // ====== 建物・場所 ======
    "家": "house", "いえ": "house",
    "学校": "school", "がっこう": "school",
    "病院": "hospital", "びょういん": "hospital",
    "城": "castle", "しろ": "castle",
    "塔": "tower", "とう": "tower",
    "東京タワー": "tower",
    "灯台": "lighthouse",
    "ピラミッド": "pyramid",
    "寺": "temple", "てら": "temple", "お寺": "temple",
    "神社": "shrine", "じんじゃ": "shrine",
    "鳥居": "torii",
    "教会": "church", "きょうかい": "church",
    "モスク": "mosque",
    "ビル": "building",
    "工場": "factory", "こうじょう": "factory",
    "ホテル": "hotel",
    "店": "shop", "みせ": "shop",
    "コンビニ": "store",
    "銀行": "bank",
    "図書館": "library",
    "博物館": "museum",
    "公園": "park",
    "遊園地": "amusement-park",
    "観覧車": "ferris-wheel",
    "ジェットコースター": "roller-coaster",
    "メリーゴーランド": "carousel",
    "テント": "tent",
    "小屋": "hut",
    "風車": "windmill",
    "水車": "water-mill",
    "橋": "bridge", "はし": "bridge",
    "トンネル": "tunnel",
    "井戸": "well",
    "墓": "grave",
    "お墓": "grave",
    "畑": "field", "畑地": "field",
    "田んぼ": "rice-field",
    "アパート": "apartment",
    "マンション": "apartment",
    "屋根": "roof", "やね": "roof",
    "煙突": "chimney",
    "窓": "window", "まど": "window",
    "扉": "door", "とびら": "door", "ドア": "door",
    "門": "gate", "もん": "gate",
    "階段": "stairs",
    "エレベーター": "elevator",
    "エスカレーター": "escalator",
    "塀": "fence",
    "柵": "fence",

    // ====== 物・道具 ======
    "本": "book", "ほん": "book",
    "雑誌": "magazine",
    "新聞": "newspaper",
    "鉛筆": "pencil", "えんぴつ": "pencil",
    "ペン": "pen",
    "ボールペン": "pen",
    "万年筆": "pen",
    "筆": "brush", "ふで": "brush",
    "クレヨン": "crayon",
    "絵の具": "paint",
    "パレット": "palette",
    "消しゴム": "eraser",
    "ハサミ": "scissors", "はさみ": "scissors",
    "定規": "ruler",
    "コンパス": "compass",
    "ホッチキス": "stapler",
    "クリップ": "paper-clip",
    "ノート": "notebook",
    "メモ": "note",
    "封筒": "envelope",
    "切手": "stamp",
    "ハガキ": "postcard", "葉書": "postcard",
    "手紙": "letter", "てがみ": "letter",
    "電話": "phone", "でんわ": "phone",
    "スマホ": "smartphone", "携帯": "cellphone",
    "テレビ": "tv", "テレビジョン": "tv",
    "ラジオ": "radio",
    "コンピューター": "computer", "パソコン": "computer", "PC": "computer",
    "ノートパソコン": "laptop", "ラップトップ": "laptop",
    "タブレット": "tablet",
    "キーボード": "keyboard",
    "マウス": "mouse",
    "プリンター": "printer",
    "カメラ": "camera",
    "ビデオカメラ": "camcorder",
    "マイク": "microphone",
    "ヘッドホン": "headphones",
    "イヤホン": "earphones",
    "スピーカー": "speaker",
    "電池": "battery",
    "コンセント": "plug",
    "電球": "lightbulb", "電灯": "lamp",
    "ランプ": "lamp",
    "ろうそく": "candle", "ロウソク": "candle", "蝋燭": "candle",
    "提灯": "lantern", "ちょうちん": "lantern",
    "ランタン": "lantern",
    "懐中電灯": "flashlight",
    "鏡": "mirror", "かがみ": "mirror",
    "時計": "clock", "とけい": "clock",
    "腕時計": "watch",
    "目覚まし": "alarm",
    "砂時計": "hourglass",
    "コンパス": "compass",
    "天秤": "scale",
    "はかり": "scale",
    "温度計": "thermometer",
    "顕微鏡": "microscope",
    "望遠鏡": "telescope",
    "双眼鏡": "binoculars",
    "虫眼鏡": "magnifier", "ルーペ": "magnifier",
    "コップ": "cup",
    "カップ": "cup",
    "マグカップ": "mug",
    "ティーカップ": "teacup",
    "グラス": "glass",
    "ボトル": "bottle",
    "ビン": "bottle", "瓶": "bottle",
    "缶": "can",
    "鍋": "pot",
    "フライパン": "pan",
    "薬缶": "kettle", "やかん": "kettle",
    "急須": "teapot", "ティーポット": "teapot",
    "皿": "plate", "さら": "plate",
    "茶碗": "bowl",
    "ボウル": "bowl",
    "箸": "chopsticks", "はし": "chopsticks",
    "スプーン": "spoon",
    "フォーク": "fork",
    "ナイフ": "knife",
    "包丁": "knife",
    "おたま": "ladle",
    "シャベル": "shovel",
    "スコップ": "shovel",
    "鍬": "hoe",
    "斧": "axe", "おの": "axe",
    "ハンマー": "hammer",
    "金槌": "hammer",
    "ドライバー": "screwdriver",
    "ペンチ": "pliers",
    "ノコギリ": "saw",
    "釘": "nail",
    "ネジ": "screw",
    "鍵": "key", "かぎ": "key",
    "錠": "lock",
    "南京錠": "padlock",
    "椅子": "chair", "いす": "chair",
    "机": "desk", "つくえ": "desk",
    "テーブル": "table",
    "ベッド": "bed",
    "ソファ": "sofa",
    "クッション": "cushion",
    "枕": "pillow", "まくら": "pillow",
    "毛布": "blanket",
    "布団": "futon",
    "棚": "shelf",
    "本棚": "bookshelf",
    "タンス": "wardrobe",
    "たんす": "wardrobe",
    "扇風機": "fan",
    "うちわ": "fan",
    "扇子": "fan",
    "エアコン": "air-conditioner",
    "ストーブ": "heater",
    "暖炉": "fireplace",
    "風呂": "bathtub",
    "シャワー": "shower",
    "トイレ": "toilet",
    "便座": "toilet",
    "歯ブラシ": "toothbrush",
    "歯磨き粉": "toothpaste",
    "石鹸": "soap",
    "シャンプー": "shampoo",
    "タオル": "towel",
    "歯磨き": "toothbrush",
    "ボール": "ball",
    "サッカーボール": "soccer-ball",
    "野球ボール": "baseball",
    "バスケットボール": "basketball",
    "テニスボール": "tennis-ball",
    "風船": "balloon", "ふうせん": "balloon",
    "凧": "kite", "たこあげ": "kite",
    "傘": "umbrella", "かさ": "umbrella",
    "かばん": "bag", "鞄": "bag", "カバン": "bag",
    "リュック": "backpack",
    "リュックサック": "backpack",
    "スーツケース": "suitcase",
    "財布": "wallet",
    "プレゼント": "gift", "ギフト": "gift",
    "贈り物": "gift",
    "リボン": "ribbon",
    "袋": "bag",
    "箱": "box", "はこ": "box",
    "宝箱": "treasure-chest",
    "ハート": "heart", "心": "heart",
    "音符": "music-note", "おんぷ": "music-note",
    "音楽": "music",

    // ====== 衣類 ======
    "シャツ": "shirt",
    "Tシャツ": "tshirt",
    "ティーシャツ": "tshirt",
    "ワイシャツ": "shirt",
    "セーター": "sweater",
    "パーカー": "hoodie",
    "ジャケット": "jacket",
    "コート": "coat",
    "ズボン": "pants",
    "パンツ": "pants",
    "ジーンズ": "jeans",
    "スカート": "skirt",
    "ドレス": "dress",
    "ワンピース": "dress",
    "着物": "kimono", "きもの": "kimono",
    "浴衣": "yukata",
    "靴": "shoe", "くつ": "shoe",
    "スニーカー": "sneaker",
    "ブーツ": "boot",
    "ハイヒール": "high-heel",
    "サンダル": "sandal",
    "靴下": "sock", "ソックス": "sock",
    "帽子": "hat", "ぼうし": "hat",
    "キャップ": "cap",
    "メガネ": "glasses", "眼鏡": "glasses",
    "サングラス": "sunglasses",
    "手袋": "glove", "てぶくろ": "glove",
    "マフラー": "scarf",
    "ネクタイ": "tie",
    "蝶ネクタイ": "bow-tie",
    "ベルト": "belt",
    "水着": "swimsuit",
    "ビキニ": "bikini",
    "下着": "underwear",
    "パジャマ": "pajamas",

    // ====== 体・顔 ======
    "顔": "face", "かお": "face",
    "笑顔": "smile", "えがお": "smile",
    "目": "eye", "め": "eye",
    "鼻": "nose", "はな": "nose",
    "口": "mouth", "くち": "mouth",
    "唇": "lips", "くちびる": "lips",
    "歯": "tooth", "は": "tooth",
    "舌": "tongue", "した": "tongue",
    "耳": "ear", "みみ": "ear",
    "髪": "hair", "かみ": "hair",
    "眉": "eyebrow",
    "ヒゲ": "mustache", "ひげ": "mustache",
    "あご": "chin",
    "頭": "head", "あたま": "head",
    "脳": "brain",
    "心臓": "heart",
    "肺": "lungs",
    "胃": "stomach",
    "骨": "bone",
    "頭蓋骨": "skull", "ドクロ": "skull", "髑髏": "skull", "スカル": "skull",
    "手": "hand", "て": "hand",
    "指": "finger", "ゆび": "finger",
    "親指": "thumb",
    "拳": "fist",
    "腕": "arm",
    "足": "foot", "あし": "foot",
    "脚": "leg",
    "膝": "knee",
    "肩": "shoulder",
    "背中": "back",
    "お腹": "stomach", "おなか": "stomach",
    "へそ": "belly",
    "赤ちゃん": "baby",
    "ベビー": "baby",
    "子供": "child", "こども": "child",
    "男の子": "boy",
    "女の子": "girl",
    "男": "man", "おとこ": "man",
    "女": "woman", "おんな": "woman",
    "おじいさん": "old-man",
    "おばあさん": "old-woman",
    "人": "person", "ひと": "person",
    "家族": "family",
    "カップル": "couple",
    "友達": "friends",

    // ====== スポーツ・遊び ======
    "サッカー": "soccer",
    "野球": "baseball", "やきゅう": "baseball",
    "バスケ": "basketball", "バスケットボール": "basketball",
    "テニス": "tennis",
    "卓球": "ping-pong",
    "バレーボール": "volleyball",
    "ラグビー": "rugby",
    "ゴルフ": "golf",
    "ボーリング": "bowling",
    "ボウリング": "bowling",
    "水泳": "swimming",
    "スイミング": "swimming",
    "サーフィン": "surf",
    "スキー": "ski",
    "スノーボード": "snowboard",
    "スケート": "skating",
    "釣り": "fishing", "つり": "fishing",
    "登山": "hiking",
    "ハイキング": "hiking",
    "キャンプ": "camping",
    "ボクシング": "boxing",
    "空手": "karate",
    "柔道": "judo",
    "剣道": "kendo",
    "弓道": "archery",
    "アーチェリー": "archery",
    "ヨガ": "yoga",
    "ダンス": "dance",
    "メダル": "medal",
    "トロフィー": "trophy",
    "賞": "award",
    "金メダル": "medal",
    "旗": "flag", "はた": "flag",
    "ゴール旗": "flag",

    // ====== 楽器・音楽 ======
    "ピアノ": "piano",
    "ギター": "guitar",
    "エレキギター": "guitar",
    "ベース": "bass",
    "バイオリン": "violin",
    "チェロ": "cello",
    "ハープ": "harp",
    "ドラム": "drum",
    "太鼓": "drum", "たいこ": "drum",
    "和太鼓": "drum",
    "シンバル": "cymbals",
    "トランペット": "trumpet",
    "ラッパ": "trumpet",
    "サックス": "saxophone",
    "サクソフォン": "saxophone",
    "フルート": "flute",
    "クラリネット": "clarinet",
    "ハーモニカ": "harmonica",
    "アコーディオン": "accordion",
    "シンセサイザー": "synthesizer",
    "マイク": "microphone",
    "メトロノーム": "metronome",
    "音符": "music-note",
    "ト音記号": "treble-clef",
    "ヘ音記号": "bass-clef",

    // ====== 仕事・職業 ======
    "医者": "doctor", "医師": "doctor",
    "看護師": "nurse",
    "警察官": "police",
    "警官": "police",
    "消防士": "firefighter",
    "兵士": "soldier",
    "シェフ": "chef", "料理人": "chef",
    "コック": "chef",
    "農家": "farmer",
    "漁師": "fisherman",
    "教師": "teacher", "先生": "teacher",
    "学生": "student",
    "科学者": "scientist",
    "宇宙飛行士": "astronaut",
    "パイロット": "pilot",
    "船長": "captain",
    "運転手": "driver",
    "建築家": "architect",
    "デザイナー": "designer",
    "画家": "painter",
    "音楽家": "musician",
    "歌手": "singer",
    "俳優": "actor",
    "女優": "actress",
    "ダンサー": "dancer",
    "魔法使い": "wizard",
    "騎士": "knight",
    "侍": "samurai",
    "忍者": "ninja",
    "海賊": "pirate",
    "王様": "king",
    "王": "king",
    "王女": "princess",
    "王子": "prince",
    "女王": "queen",

    // ====== 宇宙・SF ======
    "ロケット": "rocket",
    "宇宙船": "spaceship",
    "宇宙服": "spacesuit",
    "衛星": "satellite",
    "月面車": "rover",
    "UFO": "ufo",
    "ufo": "ufo",

    // ====== 季節・行事 ======
    "クリスマス": "christmas",
    "クリスマスツリー": "christmas-tree",
    "ツリー": "christmas-tree",
    "サンタ": "santa",
    "サンタクロース": "santa",
    "トナカイ": "reindeer",
    "プレゼント": "gift",
    "ハロウィン": "halloween",
    "かぼちゃ": "pumpkin",
    "ジャックオーランタン": "pumpkin",
    "クモの巣": "spider-web",
    "魔女": "witch",
    "誕生日": "birthday",
    "バースデー": "birthday",
    "バースデーケーキ": "birthday-cake",
    "クラッカー": "party",
    "パーティー": "party",
    "結婚": "wedding",
    "ウェディング": "wedding",
    "鯉のぼり": "carp-streamer",
    "兜": "samurai-helmet",
    "雛人形": "doll",
    "門松": "kadomatsu",
    "年賀状": "postcard",
    "節分": "demon",
    "豆まき": "demon",
    "イースター": "easter",
    "うさぎ": "rabbit",

    // ====== 記号・マーク ======
    "矢印": "arrow",
    "上矢印": "arrow-up",
    "下矢印": "arrow-down",
    "右矢印": "arrow-right",
    "左矢印": "arrow-left",
    "チェック": "check",
    "ばつ": "close", "×": "close", "バツ": "close",
    "丸": "circle", "○": "circle",
    "三角": "triangle", "△": "triangle",
    "四角": "square", "□": "square",
    "ひし形": "rhombus", "菱形": "rhombus", "ダイヤ": "diamond",
    "星": "star",
    "ハート": "heart",
    "クローバー": "clover",
    "スペード": "spade",
    "プラス": "plus", "＋": "plus",
    "マイナス": "minus", "−": "minus",
    "イコール": "equal",
    "クエスチョン": "question",
    "はてな": "question", "？": "question",
    "ビックリ": "exclamation", "！": "exclamation",
    "アット": "at", "＠": "at",
    "シャープ": "hash", "＃": "hash",
    "通貨": "money",
    "円": "yen", "￥": "yen",
    "ドル": "dollar", "＄": "dollar",
    "ユーロ": "euro",
    "パーセント": "percent",
    "無限": "infinity",
    "再生": "play",
    "停止": "stop",
    "一時停止": "pause",
    "録音": "record",
    "メニュー": "menu",
    "歯車": "gear",
    "ギア": "gear",
    "鎖": "chain",
    "錨": "anchor", "イカリ": "anchor",
    "稲妻": "lightning",
    "電撃": "lightning",
    "王冠": "crown", "クラウン": "crown",
    "ティアラ": "tiara",
    "宝石": "gem", "ジュエル": "gem",
    "ダイヤモンド": "diamond",
    "ルビー": "ruby",
    "金": "gold", "金貨": "coin",
    "銀": "silver",
    "コイン": "coin", "硬貨": "coin",
    "お金": "money", "おかね": "money", "金銭": "money",
    "札": "money",
    "札束": "money",
    "貯金箱": "piggy-bank",
    "豚の貯金箱": "piggy-bank",
    "ピン": "pin",
    "ピンマーク": "pin",
    "場所": "location",
    "地図": "map",
    "ロケーション": "location",
    "ナビ": "navigation",
    "GPS": "gps",
    "信号": "traffic-light",
    "信号機": "traffic-light",
    "標識": "sign",
    "看板": "sign",
    "メール": "mail",
    "郵便": "mail",
    "ポスト": "mailbox",
    "封筒": "envelope",
    "電話": "phone",
    "ベル": "bell",
    "鈴": "bell",
    "チャイム": "bell",
    "拡声器": "megaphone",
    "メガホン": "megaphone",
    "スピーカー": "speaker",
    "アンテナ": "antenna",
    "電波": "wifi",
    "Wi-Fi": "wifi", "WiFi": "wifi", "wifi": "wifi",
    "電源": "power",
    "オン": "power",
    "オフ": "power",
    "充電": "battery",
    "バッテリー": "battery",
    "リサイクル": "recycle",
    "再利用": "recycle",
    "禁止": "ban",
    "通行止め": "ban",
    "警告": "warning",
    "注意": "warning",
    "感謝": "thumbs-up",
    "いいね": "thumbs-up",
    "グッド": "thumbs-up",
    "サムズアップ": "thumbs-up",
    "ピース": "peace",
    "握手": "handshake",
    "拍手": "clap",
    "祈り": "pray",
    "ピストル": "gun",
    "拳銃": "gun",
    "弓": "bow",
    "矢": "arrow",
    "刀": "sword",
    "剣": "sword",
    "斧": "axe",
    "盾": "shield",
    "戦車": "tank",
    "爆弾": "bomb",
    "手榴弾": "bomb",
    "花火": "fireworks", "はなび": "fireworks",
    "線香花火": "fireworks",
    "打ち上げ花火": "fireworks",

    // ====== ピクトグラム頻出 ======
    "目玉": "eye",
    "電球": "lightbulb",
    "アイデア": "lightbulb",
    "カート": "shopping-cart",
    "ショッピングカート": "shopping-cart",
    "買い物": "shopping",
    "カレンダー": "calendar",
    "予定": "calendar",
    "スケジュール": "calendar",
    "ダウンロード": "download",
    "アップロード": "upload",
    "プリンタ": "printer",
    "プリンター": "printer",
    "印刷": "print",
    "保存": "save",
    "セーブ": "save",
    "削除": "trash",
    "ゴミ箱": "trash",
    "ごみばこ": "trash",
    "編集": "edit",
    "鉛筆マーク": "edit",
    "コピー": "copy",
    "貼り付け": "paste",
    "切り取り": "cut",
    "検索": "search",
    "虫眼鏡": "search",
    "拡大": "zoom-in",
    "縮小": "zoom-out",
    "リフレッシュ": "refresh",
    "更新": "refresh",
    "再読み込み": "refresh",
    "シェア": "share",
    "共有": "share",
    "送信": "send",
    "ハート": "heart",
    "いいねボタン": "heart",
    "お気に入り": "star",
    "お気に入り星": "star",
    "ホーム": "home",
    "アカウント": "user",
    "ユーザー": "user",
    "プロフィール": "user",
    "設定": "settings",
    "歯車設定": "gear",
    "ロック": "lock",
    "ロック解除": "unlock",
    "鍵マーク": "lock",
    "ヘルプ": "help",
    "情報": "info",
    "インフォ": "info",
    "通知": "bell",
    "ベルマーク": "bell",
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = JP_TO_EN;
  } else {
    root.PICROSS_JP_TO_EN = JP_TO_EN;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
